apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-vite
  template:
    metadata:
      labels:
        app: react-vite
    spec:
      containers:
        - name: react-vite
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
